import PDFDocument from 'pdfkit';
import fs from 'fs';

export const generateSustainabilityReport = async (hotelName: string, metrics: any) => {
  const doc = new PDFDocument();
  const path = `./reports/Report_${hotelName.replace(/\s+/g, '_')}.pdf`;
  
  doc.pipe(fs.createWriteStream(path));

  // Header
  doc.fontSize(25).text('SCOPE Sustainability Report', { align: 'center' });
  doc.fontSize(15).text(`by CarbonKeep for ${hotelName}`, { align: 'center' });
  doc.moveDown();

  // Metrics
  doc.fontSize(18).text('Performance Summary');
  doc.fontSize(12).text(`Carbon Saved: ${metrics.carbonSaved} Tons`);
  doc.fontSize(12).text(`Energy Saved: ${metrics.energySaved} kWh`);
  doc.fontSize(12).text(`Water Optimized: ${metrics.waterSaved} Liters`);
  doc.fontSize(12).text(`Sustainability Score: ${metrics.score}/100`);
  doc.moveDown();

  // AI Insights
  doc.fontSize(18).text('AI-Detected Optimization Actions');
  metrics.actions.forEach((action: string, i: number) => {
    doc.fontSize(12).text(`${i + 1}. ${action}`);
  });

  // Footer
  doc.moveDown();
  doc.fontSize(10).text('Generated by SCOPE AI Verified Systems', { align: 'center', color: 'green' });

  doc.end();
  return path;
};
